version: "2.4"

services:
  odoo:
    extends:
      file: common.yaml
      service: odoo
    restart: unless-stopped
    env_file:
      - .docker/odoo.env
      - .docker/db-access.env
    environment:
      DB_FILTER: "%h"
      DOODBA_ENVIRONMENT: "${DOODBA_ENVIRONMENT-prod}"
      INITIAL_LANG: "es_AR"
    depends_on:
      - db
    networks:
      default:
      inverseproxy_shared:
    labels:
      doodba.domain.main: "gestion.moren.com.ar"
      traefik.enable: "true"
      traefik.domain: "gestion.moren.com.ar"
      traefik.forbiddenCrawlers-0.frontend.headers.customResponseHeaders:
        "X-Robots-Tag:noindex, nofollow"
      traefik.forbiddenCrawlers-0.frontend.rule:
        Host:gestion.moren.com.ar, test.moren.com.ar,
        qa.moren.com.ar;Path:/web,/web/{anything:.*},/website/info,/website/info/{anything:.*}
      traefik.main-0.frontend.rule:
        Host:gestion.moren.com.ar, test.moren.com.ar, qa.moren.com.ar
      traefik.longpolling-0.frontend.rule:
        Host:gestion.moren.com.ar, test.moren.com.ar,
        qa.moren.com.ar;Path:/longpolling/{anything:.*}
      traefik.longpolling-0.port: 8072
      traefik.http.middlewares.do-moren-15-0-prod-buffering.buffering.retryExpression:
        IsNetworkError() && Attempts() < 5
      traefik.http.middlewares.do-moren-15-0-prod-compress.compress: "true"
      ? traefik.http.middlewares.do-moren-15-0-prod-forbid-crawlers.headers.customResponseHeaders.X-Robots-Tag
      : "noindex, nofollow"
      traefik.http.middlewares.do-moren-15-0-prod-addSTS.headers.forceSTSHeader: "true"
      traefik.http.middlewares.do-moren-15-0-prod-forceSecure.redirectScheme.scheme: https
      traefik.http.middlewares.do-moren-15-0-prod-forceSecure.redirectScheme.permanent: "true"
      traefik.http.services.do-moren-15-0-prod-main.loadbalancer.server.port: 8069
      traefik.http.services.do-moren-15-0-prod-longpolling.loadbalancer.server.port: 8072
      traefik.http.routers.do-moren-15-0-prod-main-0.rule:
        Host(`gestion.moren.com.ar`, `test.moren.com.ar`, `qa.moren.com.ar`)
      traefik.http.routers.do-moren-15-0-prod-main-0.service: do-moren-15-0-prod-main
      traefik.http.routers.do-moren-15-0-prod-main-0.middlewares:
        do-moren-15-0-prod-addSTS, do-moren-15-0-prod-buffering,
        do-moren-15-0-prod-compress, do-moren-15-0-prod-forceSecure
      traefik.http.routers.do-moren-15-0-prod-main-secure-0.rule:
        Host(`gestion.moren.com.ar`, `test.moren.com.ar`, `qa.moren.com.ar`)
      traefik.http.routers.do-moren-15-0-prod-main-secure-0.service: do-moren-15-0-prod-main
      traefik.http.routers.do-moren-15-0-prod-main-secure-0.middlewares:
        do-moren-15-0-prod-addSTS, do-moren-15-0-prod-buffering,
        do-moren-15-0-prod-compress, do-moren-15-0-prod-forceSecure
      traefik.http.routers.do-moren-15-0-prod-main-secure-0.tls: "true"
      traefik.http.routers.do-moren-15-0-prod-main-secure-0.tls.certResolver: letsencrypt
      traefik.http.routers.do-moren-15-0-prod-longpolling-0.rule:
        Host(`gestion.moren.com.ar`, `test.moren.com.ar`, `qa.moren.com.ar`) &&
        PathPrefix(`/longpolling/`)
      traefik.http.routers.do-moren-15-0-prod-longpolling-0.service: do-moren-15-0-prod-longpolling
      traefik.http.routers.do-moren-15-0-prod-longpolling-0.middlewares:
        do-moren-15-0-prod-addSTS, do-moren-15-0-prod-forceSecure
      traefik.http.routers.do-moren-15-0-prod-longpolling-secure-0.rule:
        Host(`gestion.moren.com.ar`, `test.moren.com.ar`, `qa.moren.com.ar`) &&
        PathPrefix(`/longpolling/`)
      traefik.http.routers.do-moren-15-0-prod-longpolling-secure-0.service: do-moren-15-0-prod-longpolling
      traefik.http.routers.do-moren-15-0-prod-longpolling-secure-0.middlewares:
        do-moren-15-0-prod-addSTS, do-moren-15-0-prod-forceSecure
      traefik.http.routers.do-moren-15-0-prod-longpolling-secure-0.tls: "true"
      traefik.http.routers.do-moren-15-0-prod-longpolling-secure-0.tls.certResolver: letsencrypt
      traefik.http.routers.do-moren-15-0-prod-forbiddenCrawlers-0.rule:
        Host(`gestion.moren.com.ar`, `test.moren.com.ar`, `qa.moren.com.ar`) &&
        (PathPrefix(`/web/`, `/website/info/`) || Path(`/web`, `/website/info`))
      traefik.http.routers.do-moren-15-0-prod-forbiddenCrawlers-0.service: do-moren-15-0-prod-main
      traefik.http.routers.do-moren-15-0-prod-forbiddenCrawlers-0.middlewares:
        do-moren-15-0-prod-addSTS, do-moren-15-0-prod-buffering,
        do-moren-15-0-prod-compress, do-moren-15-0-prod-forbid-crawlers,
        do-moren-15-0-prod-forceSecure
      traefik.http.routers.do-moren-15-0-prod-forbiddenCrawlers-secure-0.rule:
        Host(`gestion.moren.com.ar`, `test.moren.com.ar`, `qa.moren.com.ar`) &&
        (PathPrefix(`/web/`, `/website/info/`) || Path(`/web`, `/website/info`))
      traefik.http.routers.do-moren-15-0-prod-forbiddenCrawlers-secure-0.service: do-moren-15-0-prod-main
      traefik.http.routers.do-moren-15-0-prod-forbiddenCrawlers-secure-0.middlewares:
        do-moren-15-0-prod-addSTS, do-moren-15-0-prod-buffering,
        do-moren-15-0-prod-compress, do-moren-15-0-prod-forbid-crawlers,
        do-moren-15-0-prod-forceSecure
      traefik.http.routers.do-moren-15-0-prod-forbiddenCrawlers-secure-0.tls: "true"
      traefik.http.routers.do-moren-15-0-prod-forbiddenCrawlers-secure-0.tls.certResolver: letsencrypt

  db:
    extends:
      file: common.yaml
      service: db
    env_file:
      - .docker/db-creation.env
    restart: unless-stopped
    networks:
      default:
      inverseproxy_shared:
    labels:
      traefik.enable: "true"
      traefik.docker.network: "inverseproxy_shared"
      traefik.tcp.services.do-moren-15-0-prod-database.loadbalancer.server.port: 5432
      traefik.do-moren-15-0-prod-database-0.port: 5432
      traefik.tcp.routers.do-moren-15-0-prod-database-0.rule:
        Host(`gestion.moren.com.ar`, `test.moren.com.ar`, `qa.moren.com.ar`)
      traefik.tcp.routers.do-moren-15-0-prod-database-0.service: do-moren-15-0-prod-database

networks:
  default:
    driver_opts:
      encrypted: 1

  inverseproxy_shared:
    external: true

volumes:
  filestore:
  db:
